# Generated by Django 3.2.6 on 2021-10-03 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img',
            field=models.ImageField(blank=True, default='images/defaultimg.jpg', null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, default='images/defaultimg.jpg', null=True, upload_to='images/'),
        ),
    ]
