# Generated by Django 3.2.6 on 2021-10-03 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_userimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userimage',
            old_name='pic',
            new_name='profile',
        ),
    ]
