# Generated by Django 3.2.6 on 2022-10-01 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_commentblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentblog',
            old_name='comment',
            new_name='new_comment',
        ),
    ]
