# Generated by Django 3.2.6 on 2022-10-01 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_commentblog_asked_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentblog',
            name='blog',
        ),
    ]
